version: 2

project_name: vern

before:
  hooks:
    - cd go && go generate ./internal/embedded/

builds:
  - main: ./cmd/vern
    dir: go
    binary: vern
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "vern_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: jdonohoo
      name: homebrew-vern
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://jdonohoo.github.io/vern-bot/"
    description: "16 AI personas, multi-LLM discovery pipelines, and VernHole councils. One idea in, battle-tested plan out."
    install: |
      bin.install "vern"
    test: |
      system "#{bin}/vern", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
