//go:build ignore

// Generator: reads agents/*.md and config.default.json from the repo root,
// writes agents_generated.go with all content as Go string literals.
//
// Run: go generate ./internal/embedded/
// Or:  cd go/internal/embedded && go run gen.go

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Resolve repo root (3 levels up from go/internal/embedded/)
	repoRoot := filepath.Join("..", "..", "..")

	agentsDir := filepath.Join(repoRoot, "agents")
	configPath := filepath.Join(repoRoot, "config.default.json")

	// Read all agent files
	entries, err := os.ReadDir(agentsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read agents dir: %v\n", err)
		os.Exit(1)
	}

	type agent struct {
		name    string
		content string
	}
	var agents []agent

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), ".md")
		data, err := os.ReadFile(filepath.Join(agentsDir, entry.Name()))
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to read %s: %v\n", entry.Name(), err)
			os.Exit(1)
		}
		agents = append(agents, agent{name: name, content: string(data)})
	}

	sort.Slice(agents, func(i, j int) bool { return agents[i].name < agents[j].name })

	// Read config
	configData, err := os.ReadFile(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read config.default.json: %v\n", err)
		os.Exit(1)
	}

	// Write generated Go file
	var b strings.Builder
	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	b.WriteString("// Source: go/internal/embedded/gen.go\n")
	b.WriteString("// Regenerate: cd go && go generate ./internal/embedded/\n\n")
	b.WriteString("package embedded\n\n")

	// Agent data map
	b.WriteString("// AgentData contains all agent persona markdown files keyed by name.\n")
	b.WriteString("var AgentData = map[string]string{\n")
	for _, a := range agents {
		b.WriteString(fmt.Sprintf("\t%q: %s,\n", a.name, goStringLiteral(a.content)))
	}
	b.WriteString("}\n\n")

	// Config data
	b.WriteString("// DefaultConfigJSON contains the default config.default.json content.\n")
	b.WriteString(fmt.Sprintf("var DefaultConfigJSON = %s\n", goStringLiteral(string(configData))))

	if err := os.WriteFile("agents_generated.go", []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write agents_generated.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated agents_generated.go with %d agents\n", len(agents))
}

// goStringLiteral returns a Go string literal, using raw strings when possible.
func goStringLiteral(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}
